repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0  # Puedes usar la versión más reciente disponible
    hooks:
      - id: trailing-whitespace  # Elimina espacios en blanco al final de las líneas
      - id: end-of-file-fixer    # Asegura una línea vacía al final del archivo
      - id: check-yaml           # Verifica archivos YAML válidos
      - id: check-added-large-files  # Avisa si se agregan archivos grandes
      - id: check-merge-conflict  # Detecta conflictos de merge sin resolver

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.2.0  # Usa mypy para análisis de tipos en Python
    hooks:
      - id: mypy
